version: "3"


services:
  postgres:
    image: postgres:14.4-alpine
    container_name: "postgres"
    restart: on-failure
    # make it available from localhost
    # or use "expose: - 5432" for in-container access only
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "true_positive"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  bot:
    build: .
    container_name: "bot"
    command: ["python", "app.py"]
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://admin:admin@postgres:5432/true_positive"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src

volumes:
  postgres_data:
