version: "3"


services:
  postgres:
    image: postgres:14.4-alpine
    container_name: "postgres"
    restart: on-failure
    # make it available from localhost
    # or use "expose: - 5432" for in-container access only
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "true_positive"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chrome:
    image: selenium/node-chrome:4.3.0-20220726
    container_name: "chrome"
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.3.0-20220726
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  bot:
    build: .
    container_name: "bot"
    command: ["python", "app.py"]
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://admin:admin@postgres:5432/true_positive"
    depends_on:
      - postgres

volumes:
  postgres_data:
